import React from 'react';
import { Collapse } from 'antd';
import './css/index.css';
import locked from '../../images/faq/screenshot-locked.png';
import buy from '../../images/faq/screenshot-buy-usa.png';
import PricingDetails from '../pricing-details';

const Panel = Collapse.Panel;

const FAQ = () => (
  <div className="faq-wrapper">
    <div className="margin-vertical-large">
      <h2>Understanding MemesChain</h2>
      <Collapse bordered={false}>
      <Panel header="What is MemesChain?" key="1">
        <p>
        MemesChain is an ownership platform, that is built on the Blockchain. Blockchain powers all of the cryptocurrencies like Bitcoin and Ethereum etc. You can buy, sell, or trade your Memes, safe in the knowledge that blockchain and AI will track ownership securely ensuring your memes are not plagiarized.

        </p>
      </Panel>

      <Panel header="Ok whats the price of owning my creative memes?" key="2">
        <p>
          It's free! You can secure ownership of your memes and monetise for no cost!      
        </p>
      </Panel>

      <Panel header="Why would I want to own my meme? What does that even mean?" key="3">
        <p>
          Your memes are a reflection of your wit and creative thinking. 
          They are your innovation, which needs to be, well, kind of owned.      
        </p>
        <p>Psstt.. And everybody loves memes and witty memers</p>
      </Panel>

    </Collapse>
    </div>

    <br /> 

    <div className="margin-vertical-large">
      <h2>Artifical Intelligence &amp; MemesChain</h2>
      <Collapse bordered={false}>
      <Panel header="How does AI help me in this?" key="1">
        <p>
          It's really important to make sure your memes are not plagiarized. We use AI to make sure
           that your memes are unique and prevent people from uploading a meme which is same 
           as your's or extremely similar.
        </p>
      </Panel>
    </Collapse>
    </div>

    <br /> 

    <div className="margin-vertical-large">
      <h2>Getting started</h2>
      <Collapse bordered={false}>
        <Panel header="What do I need to own or sell memes on MemesChain?" key="1">
          <p>Here’s what you need to get started:</p>
          <ul>
            <li>A computer or laptop running the desktop version of Chrome or Firefox</li>
            <li>MetaMask, a digital wallet used specifically with web apps</li>
            <li>Ether, a form of digital payment that powers MemesChain</li>
          </ul>
        </Panel>
        <Panel header="Metamask, your digital wallet to store memes" key="2">
          <p>
            To use MemesChain, you will need to install MetaMask, a digital wallet. 
            You will need to put money in it to make your first purchase. 
            Note: A digital wallet like MetaMask is like a bank account. 
            Please store the seed words generated by metamask somewhere safe.
          </p>
          
          <div className="align-center youtube-video-container"> 
            <iframe
              width="100%"
              height="315"
              src="https://www.youtube.com/embed/tfETpi-9ORs?rel=0&amp;showinfo=0"
              frameborder="0"
              allowfullscreen=""
              title="Installing MetaMask"
            >
            </iframe>
          </div>
        </Panel>
        <Panel header="Is MetaMask locked? Why and how to unlock?" key="3">
          <p>
            Occasionally while owning memes or signing in a lock screen is displayed.
            This happens because MetaMask locks your account after a certain period of 
            time automatically. To unlock simply click on the MetaMask extension 
            and type in your password.
          </p>
          <img className="helper-images" src={locked} alt="Metamask locked"/>
        </Panel>

        <Panel header="How to buy ether, your currency to own memes" key="4">
          <p>
            <strong>For U.S. citizens only:</strong> 
            you can buy ether (ETH) in MetaMask.
            ETH is a digital currency that enables MemesChain to run.
          </p>
          <p>You can also buy via:  
            <a
              href="https://www.binance.com/?ref=26312925"
              target="_blank"
              rel="noopener noreferrer"
            > Binance </a> and
            <a
              href="https://www.coinbase.com/join/5a4c6e620f4613023d6770d4"
              target="_blank"
              rel="noopener noreferrer"
            > Coinbase </a>
          </p>
          <img className="helper-images" src={buy} alt="Buy ether"/>

          <p>
            <strong>For everyone else:</strong> you will need to purchase ETH from an exchange. 
            The easiest way is using Coinbase and then transferring the ETH from your 
            Coinbase wallet to your MetaMask wallet.<br />
            Unfortunately, you cannot own memes on the MemesChain with a Coinbase wallet 
            or any other wallets.
          </p>

          <p>
            You cannot use USD/CAD to buy a MemesChain—currencies need to be converted 
            into ETH first.
          </p>
          <p>
            <a
              href="https://www.binance.com/?ref=26312925"
              target="_blank"
              rel="noopener noreferrer"
            > Binance </a> and
            <a
              href="https://www.coinbase.com/join/5a4c6e620f4613023d6770d4"
              target="_blank"
              rel="noopener noreferrer"
            > Coinbase </a>
          </p>
        </Panel>

        <Panel header="How to send ETH to MetaMask" key="5">
          <p>
            <strong>For U.S. citizens only:</strong> You are able to purchase ETH 
            directly from the MetaMask wallet using the Coinbase widget. 
            This is more convenient and doesn’t require you to create two accounts.
          </p> <br />

          <p>
            <strong>For everyone else:</strong> You need to buy ETH from an 
            exchange using normal fiat(USD/GBP/EUR) currency. 
            Coinbase is the easiest to setup however the choice is ultimately up to you. 
            Copy your MetaMask address but clicking on the ‘...’ then ‘Copy Address to clipboard’. 
            Go to Coinbase and click ‘Accounts’ and select your ETH Wallet and 
            then click ‘send’. Paste the MetaMask address in the box with the 
            amount you’d like to transfer. <br />
          </p>

          <div className="align-center youtube-video-container">
            <iframe
              width="100%"
              height="315"
              src="https://www.youtube.com/embed/PtdMDtCVck0?rel=0&amp;showinfo=0"
              frameborder="0" 
              allowfullscreen=""
              title="Buying Ether">
            </iframe>
          </div>
        </Panel>
      </Collapse>
    </div>

    <br />       
    <div className="margin-vertical-large">
      <h2>Other</h2>
      <Collapse bordered={false}>
      <Panel header="Is MemesChain like Ethereum or Bitcon or other tokens??" key="1">
        <p>
          MemesChain is NOT a cryptocurrency. The real-world analogy for a cryptocurrency is dollars or pounds; MemesChain, is a platforms powered by blockchain to own, sell or trade your memes.
        </p>

        <p>
        As dictated by the smart contract, any memes you own belongs to you. It's upto you, to price your memes (while auctioning) based on demand.


        </p>
      </Panel>

      <Panel header="Can I use a Credit Card to start with MemesChain?" key="2">
        <p>
          Not yet; the technology simply isn’t there yet. However, as soon as it is, we plan to support it.
        </p>
        <p>
          For now, services like Coinbase allow you to buy ether with a credit card.
        </p>
      </Panel>

      <Panel header="Buying and selling?" key="3">
        <PricingDetails />
      </Panel>

      </Collapse>
      
    </div>
    </div>
);


export default FAQ;